spring.application.name=demo

spring.datasource.url=jdbc:mysql://srv1059.hstgr.io:3306/u616818059_sprint5?useSSL=false&serverTimezone=UTC

spring.datasource.username=u616818059_Javier25
spring.datasource.password=Javier@2025

# Configuración y dialecto de Hibernate para MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect